### ISSUE TITLE
Script Stolen

### ISSUE THREAD

**Issue by valandexx** [RowyHere/discord-badges-finder#1]
I have became aware that this script was copied and stolen from Elijah, delete it.

**Comment by RowyHere** [comment]
I don't know elijah, but I know that I code and share this infrastructure, how does "**elijah**" belong?

**Comment by semoizm** [comment]
> I have became aware that this script was copied and stolen from Elijah, delete it.

Such a thing is not possible. Coded by Rowy.

**Comment by valandexx** [comment]
@RowyHere lol speaking from an alt, but, remember when I mass dm'd my badge finder? (It was a trick to get your token) Then you regenerated the token on some bot named Wierzy or something.
But you removed the built-in token grabbed and rebranded this to yourself.
lol

**Comment by RowyHere** [comment]
> @RowyHere lol speaking from an alt, but, remember when I mass dm'd my badge finder? (It was a trick to get your token) Then you regenerated the token on some bot named Wierzy or something. But you removed the built-in token grabbed and rebranded this to yourself. lol

lol do you have any proof of that man? or that I stole the coding? also ahmetxsad is the one who stole my discord token
Elijah = noname coder
